In [10]:
%matplotlib inline

import glob
import os
import numpy as np
from skimage import io, segmentation, color

path = 'img/'
aFile = []


for filename in glob.glob(os.path.join(path, '*.jpg')):
    aFile.append(filename)
    
for k in range(200,400,10):
    count = np.array([0, 0, 0, 0])
    print ('min_size ->> {}'.format(k))
    for i in range(0,200):
        if(i % 50 == 0):
            print(count)
            print('----------------------------------------------')

        img = io.imread(aFile[i])
        # minsize 100 = 1, 110=2, 120=1, 130=1,140=1, 150
        labels = segmentation.felzenszwalb(img, min_size=k )
        labels = labels.astype(int)
        u = len(np.unique(labels))
        # print("Felzenszwalb number of segments: {}".format(u))
        if(i<50 and u != 2):
            count[0] = count[0] + 1
        elif(i>=50 and i<100 and u != 3):
            count[1] = count[1] + 1
        elif(i >= 100 and i<150 and u != 4):
            count[2] = count[2] + 1
        elif(i >= 150 and i<200 and u !=3):
            count[3] = count[3] + 1
        else:
            pass



    print(count)
    print('jumlah segmen unik : {}'.format(np.sum(count)))
    print('\n')

min_size ->> 200
[0 0 0 0]
----------------------------------------------
[2 0 0 0]
----------------------------------------------
[2 0 0 0]
----------------------------------------------
[ 2  0 27  0]
----------------------------------------------
[ 2  0 27  3]
jumlah segmen unik : 32


min_size ->> 210
[0 0 0 0]
----------------------------------------------
[2 0 0 0]
----------------------------------------------
[2 0 0 0]
----------------------------------------------
[ 2  0 25  0]
----------------------------------------------
[ 2  0 25  3]
jumlah segmen unik : 30


min_size ->> 220
[0 0 0 0]
----------------------------------------------
[2 0 0 0]
----------------------------------------------
[2 0 0 0]
----------------------------------------------
[ 2  0 23  0]
----------------------------------------------
[ 2  0 23  3]
jumlah segmen unik : 28


min_size ->> 230
[0 0 0 0]
----------------------------------------------
[2 0 0 0]
----------------------------------------------
[2

In [5]:
for i in range(0,10,2):
    print i

0
2
4
6
8
