In [8]:
from skimage import io 
import matplotlib.pyplot as plt
import numpy as np


img = io.imread('img\img001.jpg')
# print(img) # print nilai image original
np.set_printoptions(threshold='nan')
print(img)
print(img.shape)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 253]
  [  0   0 254]
  [  1   0 254]
  [  0   0 254]
  [  1   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [  0   0 254]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 255 255]
  [255 2